# Generated by Django 2.2.3 on 2019-08-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories_db_ui', '0002_auto_20190818_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='cat_name',
            new_name='category_name',
        ),
    ]
